jerseys = [
    {"name": "Giannis jersey",
     "price": 100,
     "image": "/static/jerseys/Giannis_jersey.jpg"},

    {"name": "Jalen Brunson",
     "price": 100,
     "image": "/static/jerseys/Jalen_Brunson_jersey.jpg",
     },

    {"name": "Anfernee Simons",
     "price": 100,
     "image": "/static/jerseys/Anfernee_Simons_jersey.jpg",
     },

    {"name": "Lebron james",
     "price": 100,
     "image": "/static/jerseys/Lebron_james_jersey.jpg",
     },

    {"name": "Luka doncic",
     "price": 100,
     "image": "/static/jerseys/luka_doncic_jersey.png",
     },

    {"name": "steph curry",
     "price": 100,
     "image": "/static/jerseys/Stephen_Curry_jersey.jpg",
     },

    {"name": "J.Suggs",
     "price": 100,
     "image": "/static/jerseys/orlado_magic_jersey.png",
     },

    {"name": "Kyle Lowry",
     "price": 100,
     "image": "/static/jerseys/toronto_raptors_jersey.png",
     },

    {"name": "Ja Morant",
     "price": 100,
     "image": "/static/jerseys/grizzlies_classic_jersey.jpg",
     },

]

tickets = [
    {
        "game_name": "Hornets vs Hawks",
        "game_description": "lets see what ice tray will do after his last game",
        "game_price": 200,
        "game_image": "/static/tickets/Hornets vs Hawks.jpg"
    },
    {
        "game_name": "Lakers vs Jazz",
        "game_description": "Exciting match up between two strong teams.",
        "game_price": 300,
        "game_image": "/static/tickets/Lakers vs Jazz.jpg"
    },
    {
        "game_name": "Spurs vs Kings",
        "game_description": "Exciting match up between two strong teams.",
        "game_price": 200,
        "game_image": "/static/tickets/Spurs vs Kings.jpg"

    },
    {
        "game_name": "Pelicans vs Spurs",
        "game_description": "Exciting match up between two strong teams.",
        "game_price": 200,
        "game_image": "/static/tickets/Pelicans vs Spurs.jpg"

    },
    {
        "game_name": "Suns vs Magic",
        "game_description": "Exciting match up between two strong teams.",
        "game_price": 200,
        "game_image": "/static/tickets/Suns vs Magic.jpg"

    },
    {
        "game_name": "Nuggets vs Hawks",
        "game_description": "Exciting match up between two strong teams.",
        "game_price": 200,
        "game_image": "/static/tickets/Nuggets vs Hawks.jpg"

    }
]

users = {
    "zura": {"fullname": "Zura Chiokadze", "age": 15, "role": "admin"},
    "andria": {"fullname": "Andria Iremadze", "age": 22, "role": "user"},
    "giorgi": {"fullname": "Giorgi Chonkadze", "age": 18, "role": "user"},
    "admin1": {"fullname": "admin", "age": 111, "role": "admin"}
}

players = [
    {
        "player": "Giannis Antetokounmpo",
        "team": "MIL",
        "gp": 17,
        "min": 35.2,
        "pts": 32.9,
        "fgm": 13.2,
        "fga": 21.6,
        "fg_pct": 60.9,
        "three_pm": 0.2,
        "three_pa": 0.8, "three_pct": 21.4,
        "ftm": 6.4, "fta": 10.5, "ft_pct": 61.2,
        "oreb": 2.1, "dreb": 9.8, "reb": 11.9,
        "ast": 6.6,
        "stl": 0.5,
        "blk": 1.4,
        "tov": 3.3,
        "eff": 37.6,
    },
    {
        "player": "Shai Gilgeous-Alexander", "team": "OKC", "gp": 30, "min": 34.7,
        "pts": 30.8, "fgm": 10.8, "fga": 21.0, "fg_pct": 51.7,
        "three_pm": 2.2, "three_pa": 6.2, "three_pct": 34.8,
        "ftm": 7.0, "fta": 8.0, "ft_pct": 87.9,
        "oreb": 0.9, "dreb": 4.7, "reb": 5.6,
        "ast": 6.1,
        "stl": 2.0,
        "blk": 1.1,
        "tov": 2.7,
        "eff": 31.8,
    },
    {
        "player": "Nikola Jokić", "team": "DEN", "gp": 27, "min": 37.1,
        "pts": 30.8, "fgm": 11.7, "fga": 20.5, "fg_pct": 57.1,
        "three_pm": 2.3, "three_pa": 4.5, "three_pct": 50.0,
        "ftm": 5.1, "fta": 6.4, "ft_pct": 79.3,
        "oreb": 1.9, "dreb": 9.5, "reb": 11.4,
        "ast": 9.5,
        "stl": 1.7,
        "blk": 0.6,
        "tov": 3.4,
        "eff": 41.5,
    },
    {
        "player": "LaMelo Ball",
        "team": "CHA",
        "gp": 22,
        "min": 33.7,
        "pts": 30.1,
        "fgm": 10.5,
        "fga": 24.6,
        "fg_pct": 42.5,
        "three_pm": 4.5,
        "three_pa": 13.0,
        "three_pct": 34.6,
        "ftm": 4.7,
        "fta": 5.5,
        "ft_pct": 84.4,
        "oreb": 0.9,
        "dreb": 4.5,
        "reb": 5.3,
        "ast": 7.4,
        "stl": 1.3,
        "blk": 0.2,
        "tov": 4.1,
        "eff": 25.3,
    },
    {
        "player": "Jayson Tatum",
        "team": "BOS",
        "gp": 28,
        "min": 36.4,
        "pts": 28.7,
        "fgm": 9.5,
        "fga": 20.4,
        "fg_pct": 46.6,
        "three_pm": 3.9,
        "three_pa": 10.5,
        "three_pct": 37.3,
        "ftm": 5.8,
        "fta": 7.2,
        "ft_pct": 80.6,
        "oreb": 0.9,
        "dreb": 6.0,
        "reb": 6.9,
        "ast": 5.6,
        "stl": 1.2,
        "blk": 1.0,
        "tov": 2.8,
        "eff": 30.5,
    },
    {
        "player": "De'Aaron Fox",
        "team": "SAC",
        "gp": 32,
        "min": 37.3,
        "pts": 26.3,
        "fgm": 9.8,
        "fga": 20.3,
        "fg_pct": 48.1,
        "three_pm": 2.0,
        "three_pa": 6.3,
        "three_pct": 32.2,
        "ftm": 4.8,
        "fta": 6.0,
        "ft_pct": 80.1,
        "oreb": 1.1,
        "dreb": 3.9,
        "reb": 5.0,
        "ast": 6.3,
        "stl": 1.7,
        "blk": 0.3,
        "tov": 3.4,
        "eff": 24.5,
    },
    {
        "player": "Anthony Davis",
        "team": "LAL",
        "gp": 30,
        "min": 34.7,
        "pts": 26.0,
        "fgm": 9.4,
        "fga": 17.8,
        "fg_pct": 52.7,
        "three_pm": 0.7,
        "three_pa": 2.1,
        "three_pct": 31.3,
        "ftm": 6.6,
        "fta": 8.5,
        "ft_pct": 77.6,
        "oreb": 2.6,
        "dreb": 8.9,
        "reb": 11.5,
        "ast": 3.5,
        "stl": 1.2,
        "blk": 2.0,
        "tov": 2.2,
        "eff": 31.8,
    },
    {
        "player": "Tyrese Maxey",
        "team": "PHI",
        "gp": 23,
        "min": 37.2,
        "pts": 26.0,
        "fgm": 9.0,
        "fga": 21.4,
        "fg_pct": 42.0,
        "three_pm": 3.3,
        "three_pa": 9.6,
        "three_pct": 33.9,
        "ftm": 4.7,
        "fta": 5.7,
        "ft_pct": 82.6,
        "oreb": 0.9,
        "dreb": 3.5,
        "reb": 4.3,
        "ast": 7.7,
        "stl": 0.5,
        "blk": 0.2,
        "tov": 3.5,
        "eff": 22.0,
    },
    {
        "player": "Damian Lillard",
        "team": "MIL",
        "gp": 23,
        "min": 36.3,
        "pts": 25.9,
        "fgm": 7.9,
        "fga": 17.7,
        "fg_pct": 44.8,
        "three_pm": 3.6,
        "three_pa": 9.3,
        "three_pct": 36.9,
        "ftm": 6.6,
        "fta": 7.2,
        "ft_pct": 92.1,
        "oreb": 0.6,
        "dreb": 4.0,
        "reb": 4.6,
        "ast": 7.7,
        "stl": 1.1,
        "blk": 0.2,
        "tov": 2.9,
        "eff": 26.3,
    },
    {
        "player": "Jalen Brunson",
        "team": "NYK",
        "gp": 32,
        "min": 34.9,
        "pts": 25.5,
        "fgm": 8.7,
        "fga": 17.8,
        "fg_pct": 48.7,
        "three_pm": 2.6,
        "three_pa": 6.3,
        "three_pct": 41.0,
        "ftm": 5.6,
        "fta": 6.8,
        "ft_pct": 82.1,
        "oreb": 0.4,
        "dreb": 2.5,
        "reb": 3.0,
        "ast": 7.7,
        "stl": 0.8,
        "blk": 0.1,
        "tov": 2.4,
        "eff": 24.3,
    },

    {"player": "Goga Bitadze",
     "team": "ORL",
     "gp": 31,
     "min": 24.8,
     "pts": 9.9,
     "fgm": 4.1,
     "fga": 6.5,
     "fg_pct": 63.1,
     "three_pm": 0.0,
     "three_pa": 0.5,
     "three_pct": 6.3,
     "ftm": 1.6,
     "fta": 2.3,
     "ft_pct": 71.4,
     "oreb": 3.0,
     "dreb": 5.5,
     "reb": 8.5,
     "ast": 2.4,
     "stl": 0.9,
     "blk": 1.6,
     "tov": 1.5,
     "eff": 24.3, }
]

newses = [{"title": "ბითაძის მე-10 ორმაგი დუბლი | გოგა ორლანდოს ისტორიული შედეგის გამეორებაში დაეხმარა",
           "author": "GBF",
           "date": "2024-12-22",
           "image": "/static/news/goga_bitadze_news.png",
           "news": '''გოგა ბითაძის მორიგი შედეგიანი თამაში და ორლანდოს გამარჯვება მაიამი ჰითთან. ორლანდოელთა ქართველმა ცენტრმა მიმდინარე სეზონში მე-10 ორმაგი დუბლი შეასრულა და მეჯიქს ფლორიდული დერბის მოგებაში დიდად დაეხმარა. ზედიზედ 3 წაგების შემდეგ ორლანდომ მოახერხა ნავსის გატეხვა და მაიამის საშინაო შეხვედრაში 121:114 სძლია.
                    ორლანდომ პირველი პერიოდიც წააგო, მეორეც და მესამეც. ბოლო მეოთხედის წინ 22 ქულით ჩამორჩებოდა, თუმცა სასწაული ქამბექი მოახდინა და დასკვნითი პერიოდის 37:8 მოგებით საამაყო გამარჯვება მოიპოვა. ორლანდო 25 ქულითაც აგებდა და ასეთი ჩამორჩენის შემდეგ მოგებით ისტორიული შედეგი გაიმეორა. აქამდე მეჯიქს სწორედ 25-ქულიანი ჩამორჩენის შემდეგ მოგება ჰქონდა უმაღლეს შედეგად, რომელიც 1989 წლის 8 ნოემბერს, კლივლენდ კავალესთან მატჩში შეძლო. ისტორია დღეს, ქართველი ცენტრის თანამონაწილეობით გამეორდა. 
                    რაც ყველაზე მნიშვნელოვანია, გოგა მოედანზე იყო  ბოლო პერიოდის უმეტეს დროს. განსაკუთრებით გამოსარჩევია მისი 6 ქულა (3 ორქულიანი) შეხვედრის ბოლო 4 წუთში. ბითაძემ ჯერ სირენამდე 3:59 წუთით ადრე ჩააგდო და ორლანდო 106:109 მიაახლოვა მაიამისთან. შემდეგ სირენამდე 1:35-ით ადრე და თავისი გუნდი 112:100 დააწინაურა. ბოლო ბურთი კი ქართველმა ცენტრმა დასრულებამდე 30 წამით ადრე მიითვალა, ანგარიში 117:112 გახადა და მეჯიქს ფაქტობრივად გამარჯვება გაუნაღდა.
                    ბითაძე იყო ერთადერთი მოთამაშე მოედანზე, რომელმაც ორმაგი დუბლი შეასრულა. ის სასტარტო ხუთეულში იყო და მოედანზე 31 წუთი გაატარა, რა დროშიც თამაშიდან ბურთი არ აუცილებია. მან 8-დან 8 ორქულიანი და 3-დან 2 საჯარიმო ჩააგდო: 18 ქულა, 13 მოხსნა, 2 დაფარება, 1 პასი. ბითაძემ 3 ჯარიმა მიიღო და ბურთი არ დაუკარგავს. ბითაძე დომინირებდა ორივე ფარის ქვეშ და მატჩის ერთ-ერთი მთავარი ფიგურა გახლდათ.
                    ორლანდოში 35 ქულითა და 9 პასით კოულ ენტონი გამოირჩა, კენტავიუს პოუპმა კი 24 ქულა დააგროვა. მაიამიში 23-23 ქულით ადებაიო და ტერი როზიე გამოირჩნენ. 
                    18 მოგებით და 12 მარცხით ორლანდო აღმოსავლეთ კონფერენციაში მე-4 ადგილზეა. მეჯიქს ნიუ იორკმა გადაასწრო, რომელსაც 18 მოგება და 10 მარცხი აქვს. მორიგ მატჩს ორლანდო 24 დეკემბერს, შინ ბოსტონ სელტიქსთან გამართავს.''',
           "link": "https://www.youtube.com/embed/jiYTuYgzGGA"},

          {"title": "შერმადინის MVP-ის ტიტული და ტენერიფეს გამარჯვება მურსიასთან",
           "author": "GBF",
           "date": "2024-12-22",
           "image": "/static/news/shermadini_news1.jpg",
           "news": '''მცირე პაუზის შემდეგ გიორგი შერმადინმა მატჩის MVP-ის ტიტული მოიპოვა. ეს მოხდა ესპანეთის ჩემპიონატის მორიგ ტურში, რომელშიც ლაგუნა ტენერიფემ მურსია 82:74 დაამარცხა. მურსიამ პირველი ტაიმი 33:32 მოიგო, რის შემდეგაც ტენერიფემ მეტოქეს მესამე პერიოდში 10 ქულით მოუგო (25:15) და ეს უპირატესობა შეხვედრის ბოლომდე შეინარჩუნა.
                    ქართველი ცენტრი სასტარტო ხუთეულში იყო და მოედანზე 22:55 წუთი გაატარა, რა დროშიც 14 ქულა, 5 მოხსნა და 1 პასი დააგროვა. შერმადინმა 5-დან 4 ორქულიანი და 8-დან 6 საჯარიმო სროლა ჩააგდო. გიორგი შეხვედრის MVP გახდა. ტენერიფეს საუკეთესო მექულე კი მარსელინო უერტასი იყო, რომელმაც შეხვედრა 23 ქულით დაასრულა.
                    ტენერიფე მომდევნო ტურში შერმადინის ყოფილ გუნდს ანდორას შეხვდება. გიორგის კლუბს მიმდინარე სეზონში 8 მოგება და 4 მარცხი დაუგროვდა. ტენერიფე 16 ქულით მეოთხე ადგილზეა.''',
           "link": ""
           },

          {"title": "სუპერლიგის ერთადერთ დაუმარცხებელ გუნდ თსუ-ს გურჯაანმა თბილისში მოუგო",
           "author": "GBF",
           "date": "2024-12-21",
           "image": "/static/news/super_league_news.jpg",
           "news": '''სუპერლიგაში დაუმარცხებელი გუნდი აღარ არის. ერთადერთი თსუ იყო, რომელსაც წაგება არ ჰქონდა თუმცა დღემდე. თბილისის სახელმწიფო უნივერსიტეტის გუნდმა გასული 8 ტურის მატჩი მოიგო, მე-9-ში დაისვენა და დღეს, თბილისი არენაზე გურჯაანის “დელტას” უმასპინძლა. სწორედ ამ მატჩში შეწყდა თსუ-ს წაუგებელი სერია. ლექსო ლაფანაშვილის გაწვრთნილმა გუნდმა კახეთის წარმომადგენელთან 88:99 (სტატისტიკა) წააგო.

არადა, დელტას აქამდე 4 წაგება და 5 მოგება ჰქონდა. ირაკლი ხოშტარიას გაწვრთნილი გუნდი ფავორიტად არ ითვლებოდა, თუმცა ისე ითამაშა, მოგება დაიმსახურა. თსუ-ს გიორგი ცინცაძე აკლდა, თუმცა უკანა ხაზში მატება ჰქონდა. გუნდში პირველად ითამაშა ახალბედა გამთამაშებელმა გლენ აბრამმა, რომელიც აქტიური კი იყო, თუმცა ეფექტურობა და შედეგიანობა აკლდა. 

შესაბამისად, თსუ-ს უკანა ხაზში გაუჭირდა, თამაშს ალღო ვერ აუღო ვერც უნივერსიტეტელთა ცენტრმა, კარსონ ბაშამმა. თსუ-ს ლიდერი ალექსანდრე ფევაძე სანამ მოედანზე იყო, თსუ-ს არ უჭირდა, თუმცა თამაშის დასრულებამდე 6:30 წუთით ადრე, როცა ანგარიში 74:74 იყო ფევაძეს 5 პერსონალურის გამო მოედნის დატოვება მოუხდა. რთული სათქმელია, ამის გამო მოხდა თუ არა, მაგრამ 3 წუთში ანგარიში გურჯაანელებმა წაიყვანეს – 82:76.  

მომდევნო 3 წუთში კი მატჩის ბედიც გადაწყდა. სკილერ პოტერის, საბა ლობჯანიძის და დანია კინგსბის შედეგიანი თამაშით დელტა 91:79 დაწინაურდა და დარჩენილ 1:20 წუთში თსუ-ს თამაშის გადარჩენის შანსი წაერთვა. გურჯაანელთა რიგებში 16 ქულით, 10 პასით, 6 მოხსნითა და 4 ჩჭრით საბა ლობჯანიძე გამოირჩა. 21 ქულა მიითვალა ჯორდან სვოპშირმა, სკილერ პოტერის ანგარიშზე კი 20 ქულა და 7 მოხსნა დაგროვდა. დანია კინგსბი გურჯაანელებს 19 ქულით შეეხიდა. თსუ-ში 22 ქულითა და 5 პასით საუკეთესო იყო ნიკოლოზ გაფრინდაშვილი15 ქულა და 9 მოხსნა ალექსანდრე ფევაძემ მიითვალა. 16 ქულა დევონტრე ტომასმა მიითვალა. დებიუტი 7 ქულითა და 3 პასით აღნიშნა თსუ-ს ახალწვეულმა გლენ აბრამმა. 

წაგების მიუხედავად თსუ ერთპიროვნულ ლიდერობას ინარჩუნებს, დელტას კი მეორე ადგილზეა, რომელსაც მატჩითა და წაგებით მეტი აქვს, ვიდრე კონკურენტების ტრიოს – მარგვეთს, ვსა-ს და ქუთაისს. სუპერლიგის მე-10 ტურის დარჩენილი 2 მატჩი ხვალ, 22 დეკემბერს გაიმართება. ვსა დიღმის არენაზე ტყიბულის ორბს უმასპინძლებს, ხოლო ივერიონი გორში ქუთაისს მიიღებს.''',
           "link": ""}

          ]

championships = [
    {"name": "superleague",
     "country": "Georgia",
     "official_site": "http://superleague.ge/en/",
     "logo": "/static/championships/gbf.jpg"},

    {"name": "NBA",
     "country": "United States",
     "official_site": "https://www.nba.com/",
     "logo": "/static/championships/logo-nba.png"},

    {"name": "seria A",
     "country": "Italia",
     "official_site": "https://www.legabasket.it/",
     "logo": "/static/championships/LegaBasket_Serie_A_Logo.jpg"},

]

eastern_teams = [
    {"name": "Cleveland Cavaliers", "image": "/static/nba_team_logos/Eastern_Conference/Cleveland.png", "W": 28, "L": 4,
     "win_percentage": .875, "GB": 0, "CONF": "20-4", "DIV": "6-0", "HOME": "17-1", "ROAD": "11-3", "Neutral": "0-0",
     "OT": "0-0", "LAST10": "9-1", "STREAK": "W7"},
    {"name": "Boston Celtics", "image": "/static/nba_team_logos/Eastern_Conference/Boston.png", "W": 23, "L": 9,
     "win_percentage": .719, "GB": 5, "CONF": "21-7", "DIV": "4-1", "HOME": "12-6", "ROAD": "11-3", "Neutral": "0-0",
     "OT": "2-1", "LAST10": "5-5", "STREAK": "L1"},
    {"name": "New York Knicks", "image": "/static/nba_team_logos/Eastern_Conference/New York knick.png", "W": 23,
     "L": 10, "win_percentage": .697, "GB": 5.5, "CONF": "17-7", "DIV": "5-1", "HOME": "10-4", "ROAD": "13-6",
     "Neutral": "0-0", "OT": "1-0	", "LAST10": "9-1", "STREAK": "W8"},
    {"name": "Orlando magic", "image": "/static/nba_team_logos/Eastern_Conference/Orlando_logo.svg", "W": 20, "L": 14,
     "win_percentage": .588, "GB": 9, "CONF": "16-9", "DIV": "5-1", "HOME": "13-4", "ROAD": "7-10", "Neutral": "0-0",
     "OT": "0-0	", "LAST10": "4-6", "STREAK": "W1"},
    {"name": "Atlanta Hawks", "image": "/static/nba_team_logos/Eastern_Conference/Atlanta hawk.png", "W": 18, "L": 15,
     "win_percentage": .545, "GB": 10.5, "CONF": "13-7", "DIV": "4-2", "HOME": "10-7", "ROAD": "8-7", "Neutral": "0-1",
     "OT": "1-1", "LAST10": "6-4", "STREAK": "W4"},
    {"name": "milwaukee bucks", "image": "/static/nba_team_logos/Eastern_Conference/milwaukee bucks.png", "W": 16,
     "L": 14, "win_percentage": .533, "GB": 11, "CONF": "14-13", "DIV": "5-5", "HOME": "10-5", "ROAD": "5-9",
     "Neutral": "1-0", "OT": "1-0", "LAST10": "5-5", "STREAK": "L2"},
    {"name": "Miami Heat", "image": "/static/nba_team_logos/Eastern_Conference/Miami_Heat_logo.svg", "W": 16, "L": 14,
     "win_percentage": .533, "GB": 11, "CONF": "11-10", "DIV": "5-5", "HOME": "10-5", "ROAD": "5-9", "Neutral": "1-0",
     "OT": "1-0", "LAST10": "5-5", "STREAK": "L2"},
    {"name": "Indiana Pacers", "image": "/static/nba_team_logos/Eastern_Conference/Indiana_logo.svg", "W": 16, "L": 18,
     "win_percentage": .471, "GB": 13.5, "CONF": "9-14", "DIV": "2-3", "HOME": "8-6", "ROAD": "8-12", "Neutral": "0-0",
     "OT": "1-1", "LAST10": "6-4", "STREAK": "L1"},
    {"name": "Chicago Bulls", "image": "/static/nba_team_logos/Eastern_Conference/Chicago_logo.svg", "W": 15, "L": 18,
     "win_percentage": .455, "GB": 14, "CONF": "10-13", "DIV": "	1-5", "HOME": "6-8", "ROAD": "9-10",
     "Neutral": "0-0", "OT": "2-2", "LAST10": "6-4", "STREAK": "W2"},
    {"name": "Detroit Piston", "image": "/static/nba_team_logos/Eastern_Conference/Detroit_logo.svg", "W": 14, "L": 18,
     "win_percentage": .438, "GB": 14.5, "CONF": "10-14", "DIV": "	1-5", "HOME": "6-8", "ROAD": "9-10",
     "Neutral": "0-0", "OT": "2-2", "LAST10": "6-4", "STREAK": "L1"},
    {"name": "Philadelphia 76ers", "image": "/static/nba_team_logos/Eastern_Conference/Philadelphia_logo.svg", "W": 13,
     "L": 17, "win_percentage": .433, "GB": 14.5, "CONF": "10-9", "DIV": "2-2", "HOME": "5-8", "ROAD": "8-9",
     "Neutral": "0-0", "OT": "1-0", "LAST10": "8-2", "STREAK": "W1"},
    {"name": "Brooklyn Nets", "image": "/static/nba_team_logos/Eastern_Conference/Brooklyn_logo.svg", "W": 12, "L": 20,
     "win_percentage": .375, "GB": 16.5, "CONF": "6-16", "DIV": "1-6", "HOME": "5-9", "ROAD": "7-10", "Neutral": "0-0",
     "OT": "0-2", "LAST10": "3-7", "STREAK": "L2"},
    {"name": "Charlotte Hornets", "image": "/static/nba_team_logos/Eastern_Conference/Charlotte_logo.svg", "W": 7,
     "L": 25, "win_percentage": .219, "GB": 21.5, "CONF": "4-15", "DIV": "2-5", "HOME": "5-13", "ROAD": "2-12",
     "Neutral": "0-0", "OT": "1-2", "LAST10": "1-9", "STREAK": "L8"},
    {"name": "Toronto Raptors", "image": "/static/nba_team_logos/Eastern_Conference/TorontoRaptors_logo.svg", "W": 7,
     "L": 26, "win_percentage": .212, "GB": 22, "CONF": "6-22", "DIV": "0-8", "HOME": "5-13", "ROAD": "1-12",
     "Neutral": "0-0", "OT": "1-2", "LAST10": "0-10", "STREAK": "L11"},
    {"name": "Washington Wizards", "image": "/static/nba_team_logos/Eastern_Conference/WashingtonWizards.svg", "W": 5,
     "L": 25, "win_percentage": .167, "GB": 22.5, "CONF": "5-17", "DIV": "4-3", "HOME": "5-12", "ROAD": "1-12",
     "Neutral": "0-0", "OT": "0-1", "LAST10": "3-7", "STREAK": "L2"},
    ]

western_teams= [    {"name": "Oklahoma City Thunder", "image": "/static/nba_team_logos/Western_Conference/Oklahoma_City_logo.svg",
     "W": 29, "L": 5,
     "win_percentage": .853, "GB": 0, "CONF": "19-5", "DIV": "5-1", "HOME": "15-2", "ROAD": "13-3",
     "Neutral": "1-0", "OT": "0-0", "LAST10": "10-0", "STREAK": "W14"},

    {"name": "Houston Rockets", "image": "/static/nba_team_logos/Western_Conference/Houston_logo.svg", "W": 22, "L": 12,
     "win_percentage": .647, "GB": 7, "CONF": "14-8", "DIV": "7-1", "HOME": "12-6", "ROAD": "10-5",
     "Neutral": "0-1", "OT": "2-1", "LAST10": "6-4", "STREAK": "L1"},

    {"name": "Memphis Grizzlies", "image": "/static/nba_team_logos/Western_Conference/Memphis_logo.svg", "W": 23,
     "L": 13,
     "win_percentage": .639, "GB": 7, "CONF": "10-10", "DIV": "2-2", "HOME": "14-4", "ROAD": "9-9",
     "Neutral": "0-0", "OT": "0-0", "LAST10": "5-5", "STREAK": "L2"},

    {"name": "Denver Nuggets", "image": "/static/nba_team_logos/Western_Conference/Denver_logo.svg", "W": 20, "L": 14,
     "win_percentage": .588, "GB": 9, "CONF": "13-10", "DIV": "4-3", "HOME": "10-6", "ROAD": "10-8",
     "Neutral": "0-0", "OT": "4-0", "LAST10": "6-4", "STREAK": "W1"},

    {"name": "Los Angeles Lakers", "image": "/static/nba_team_logos/Western_Conference/Los Angeles_logo.svg", "W": 20,
     "L": 14,
     "win_percentage": .588, "GB": 9, "CONF": "16-7", "DIV": "6-2", "HOME": "12-5", "ROAD": "8-9",
     "Neutral": "0-0", "OT": "0-0", "LAST10": "7-3", "STREAK": "W2"},

    {"name": "Dallas Mavericks", "image": "/static/nba_team_logos/Western_Conference/Dallas_logo.svg", "W": 20, "L": 15,
     "win_percentage": .571, "GB": 9.5, "CONF": "14-12", "DIV": "4-2", "HOME": "10-6", "ROAD": "10-9",
     "Neutral": "0-0", "OT": "0-1", "LAST10": "4-6", "STREAK": "L4"},

    {"name": "LA Clippers", "image": "/static/nba_team_logos/Western_Conference/clippers_logo.svg", "W": 20, "L": 15,
     "win_percentage": .571, "GB": 9.5, "CONF": "14-14", "DIV": "5-2", "HOME": "12-6", "ROAD": "8-9",
     "Neutral": "0-0", "OT": "0-1", "LAST10": "6-4", "STREAK": "W1"},

    {"name": "Golden State Warriors", "image": "/static/nba_team_logos/Western_Conference/Golden State_logo.svg",
     "W": 18,
     "L": 16,
     "win_percentage": .529, "GB": 11, "CONF": "14-12", "DIV": "1-5", "HOME": "10-8", "ROAD": "8-8",
     "Neutral": "0-0", "OT": "1-0", "LAST10": "4-6", "STREAK": "W2"},

    {"name": "San Antonio Spurs", "image": "/static/nba_team_logos/Western_Conference/San Antonio_logo.svg", "W": 18,
     "L": 17,
     "win_percentage": .514, "GB": 11.5, "CONF": "15-14", "DIV": "2-4", "HOME": "12-8", "ROAD": "6-9",
     "Neutral": "0-0", "OT": "1-1", "LAST10": "5-5", "STREAK": "L1"},

    {"name": "Minnesota Timberwolves", "image": "/static/nba_team_logos/Western_Conference/Minnesota_logo.svg", "W": 17,
     "L": 17,
     "win_percentage": .500, "GB": 12, "CONF": "14-10", "DIV": "2-3", "HOME": "9-7", "ROAD": "8-10",
     "Neutral": "0-0", "OT": "1-1", "LAST10": "4-6", "STREAK": "L3"},

    {"name": "Sacramento Kings", "image": "/static/nba_team_logos/Western_Conference/Sacramento_logo.svg", "W": 16,
     "L": 19,
     "win_percentage": .457, "GB": 13.5, "CONF": "12-14", "DIV": "2-6", "HOME": "9-12", "ROAD": "7-7",
     "Neutral": "0-0", "OT": "1-2", "LAST10": "4-6", "STREAK": "W3"},

    {"name": "Phoenix Suns", "image": "/static/nba_team_logos/Western_Conference/Phoenix_logo.svg", "W": 15, "L": 18,
     "win_percentage": .455, "GB": 13.5, "CONF": "13-10", "DIV": "5-4", "HOME": "10-8", "ROAD": "5-10",
     "Neutral": "0-0", "OT": "1-1", "LAST10": "3-7", "STREAK": "L4"},

    {"name": "Portland Trail Blazers", "image": "/static/nba_team_logos/Western_Conference/Portland_logo.svg", "W": 12,
     "L": 22,
     "win_percentage": .353, "GB": 17, "CONF": "10-20", "DIV": "4-4", "HOME": "8-8", "ROAD": "4-14",
     "Neutral": "0-0", "OT": "0-0", "LAST10": "4-6", "STREAK": "W1"},

    {"name": "Utah Jazz", "image": "/static/nba_team_logos/Western_Conference/Utah_logo.svg", "W": 8, "L": 25,
     "win_percentage": .242, "GB": 20.5, "CONF": "3-21", "DIV": "1-5", "HOME": "2-12", "ROAD": "6-13",
     "Neutral": "0-0", "OT": "0-0", "LAST10": "3-7", "STREAK": "W1"},

    {"name": "New Orleans Pelicans", "image": "/static/nba_team_logos/Western_Conference/New Orleans_logo.svg", "W": 6,
     "L": 29,
     "win_percentage": .171, "GB": 23.5, "CONF": "3-17", "DIV": "0-6", "HOME": "5-14", "ROAD": "1-15",
     "Neutral": "0-0", "OT": "0-0", "LAST10": "1-9", "STREAK": "L3"}

]

games = [
    {"team_1": "NYK",
     "team_2": "WAS",
     "team_1_img": "/static/nba_team_logos/Eastern_Conference/New York knick.png",
     "team_2_img": "/static/nba_team_logos/Eastern_Conference/WashingtonWizards.svg",
     "final_score": "126-106"},

    {"team_1": "CHI",
     "team_2": "CHA",
     "team_1_img": "/static/nba_team_logos/Eastern_Conference/Chicago_logo.svg",
     "team_2_img": "/static/nba_team_logos/Eastern_Conference/Charlotte_logo.svg",
     "final_score": "115-108"},

    {"team_1": "BKN",
     "team_2": "TOR",
     "team_1_img": "/static/nba_team_logos/Eastern_Conference/Brooklyn_logo.svg",
     "team_2_img": "/static/nba_team_logos/Eastern_Conference/TorontoRaptors_logo.svg",
     "final_score": "116-113"},

    {"team_1": "DET",
     "team_2": "ORL",
     "team_1_img": "/static/nba_team_logos/Eastern_Conference/Detroit_logo.svg",
     "team_2_img": "/static/nba_team_logos/Eastern_Conference/Orlando_logo.svg",
     "final_score": "132-121"},

]
